Week_4/Activity 5/activity5/src/main/java/beans/Album.java
package beans;

import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * ---------------------------------------------------------------
 * Name      : Kelly Lamb
 * Date      : 2022-02-14
 * Class     : CST-361 Design Patterns with Java
 * Professor : Mohamed Mneimneh
 * Assignment: Activity 4
 * Disclaimer: This is our own work
 * ---------------------------------------------------------------
 * Description:
 * 1. Class defining a music album
 * 2.
 * 3.
 * ---------------------------------------------------------------
 */
@ManagedBean
@ViewScoped
public class Album
{
	@NotNull(message="Title cannot be empty")
	@Size(min=5, max=50, message="Title length must be between 5-50 characters") 
	private String title;
	
	@NotNull(message="Artist cannot be empty")
	@Size(min=5, max=25, message="Artist length must be between 5-25 characters") 
	private String artist;

	@Min(value = 1920, message="Year cannot be less than 1920")
	@Max(value = 2020, message="Year cannot be greater than 2020")
	@NotNull(message="Year cannot be empty")
	private int year;

	private List<Track> tracks;

	/**
	 * Default Constructor
	 */
	public Album()
	{
		this.title = "";
		this.artist = "";
		this.year = 0;
		this.tracks = new ArrayList<Track>();
	}

	/**
	 * @param title String title of album
	 * @param artist String name of the artist or musical group
	 * @param year int year album was released
	 *  
	 */
	public Album(String title, String artist, int year)
	{
		this.title = title;
		this.artist = artist;
		this.year = year;
		this.tracks = new ArrayList<Track>();
	}
	
	/**
	 * @return the title
	 */
	public int getNumberTracks()
	{
		return this.tracks.size();
	}

	/**
	 * @return the title
	 */
	public String getTitle()
	{
		return title;
	}

	/**
	 * @param title the title to set
	 */
	public void setTitle(String title)
	{
		this.title = title;
	}

	/**
	 * @return the artist
	 */
	public String getArtist()
	{
		return artist;
	}

	/**
	 * @param artist the artist to set
	 */
	public void setArtist(String artist)
	{
		this.artist = artist;
	}

	/**
	 * @return the year
	 */
	public int getYear()
	{
		return year;
	}

	/**
	 * @param year the year to set
	 */
	public void setYear(int year)
	{
		this.year = year;
	}

	/**
	 * @return the tracks
	 */
	public List<Track> getTracks()
	{
		return tracks;
	}

	/**
	 * @param tracks the tracks to set
	 */
	public void setTracks(List<Track> tracks)
	{
		this.tracks = tracks;
	}
}

Week_4/Activity 5/activity5/src/main/java/beans/Track.java
package beans;

/**
 * ---------------------------------------------------------------
 * Name      : Kelly Lamb
 * Date      : 2022-02-14
 * Class     : CST-361 Design Patterns with Java
 * Professor : Mohamed Mneimneh
 * Assignment: Activity 4
 * Disclaimer: This is our own work
 * ---------------------------------------------------------------
 * Description:
 * 1. Class defining a track for a music album
 * 2.
 * 3.
 * ---------------------------------------------------------------
 */

public class Track
{
	private String title;
	private int number;

	/**
	 * Default Constructor
	 */
	public Track()
	{
		this.title = "";
		this.number = 0;
	}

	/**
	 * Non-Default Constructor
	 */
	public Track(String title, int number)
	{
		this.title = title;
		this.number = number;
	}

	/**
	 * @return the title
	 */
	public String getTitle()
	{
		return title;
	}

	/**
	 * @param title the title to set
	 */
	public void setTitle(String title)
	{
		this.title = title;
	}

	/**
	 * @return the number
	 */
	public int getNumber()
	{
		return number;
	}

	/**
	 * @param number the number to set
	 */
	public void setNumber(int number)
	{
		this.number = number;
	}
}

Week_4/Activity 5/activity5/src/main/java/controllers/AlbumController.java
package controllers;


import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import beans.Album;
import business.MusicManager;
import business.MusicManagerInterface;
import util.AlbumNotFoundException;
import util.TracksNotFoundException;

/**
 * ---------------------------------------------------------------
 * Name      : Kelly Lamb
 * Date      : 2022-02-114
 * Class     : CST-361 Design Patterns with Java
 * Professor : Mohamed Mneimneh
 * Assignment: Activity 4
 * Disclaimer: This is our own work
 * ---------------------------------------------------------------
 * Description:
 * 1. Class defining a controller for album management
 * 2.
 * 3.
 * ---------------------------------------------------------------
 */
@ManagedBean
@ViewScoped
public class AlbumController
{	
	MusicManagerInterface manager;
	
	public AlbumController()
	{
		manager = new MusicManager();
	}
	
	public String onSubmit(Album album) 
	{
		
		try
		{
			album = manager.addAlbum(album);
		}
		catch(TracksNotFoundException e)
		{
			System.out.println(e.getMessage());
			
			// Add View Faces Message
			FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, e.getMessage(), e.getMessage());
			// The component id is null, so this message is considered as a view message
			FacesContext.getCurrentInstance().addMessage(null, message);
			// Return empty token for navigation handler
			return "";
		}
		
		FacesContext.getCurrentInstance().getExternalContext().getRequestMap().put("album", album);
        
        return "AddAlbumResponse.xhtml";
	}
	
	public String onFind(Album album) 
	{
		try
		{
			album = manager.getAlbum(album);
		}
		catch(AlbumNotFoundException e)
		{
			System.out.println(e.getMessage());
			
			// Add View Faces Message
			FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, e.getMessage(), e.getMessage());
			// The component id is null, so this message is considered as a view message
			FacesContext.getCurrentInstance().addMessage(null, message);
			// Return empty token for navigation handler
			return "";
		}
		
		FacesContext.getCurrentInstance().getExternalContext().getRequestMap().put("album", album);
        
        return "AddAlbumResponse.xhtml";
	}
}

Week_4/Activity 5/activity5/src/main/webapp/AddAlbumForm.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:ui="http://java.sun.com/jsf/facelets"
	  xmlns:h="http://java.sun.com/jsf/html"
	  xmlns:f="http://java.sun.com/jsf/core">
	  
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
	<title><ui:insert name="pageTitle">Add Music Album</ui:insert></title>
    <h:outputStylesheet library="css" name="styles.css"/>
</h:head>

<h:body>
    <ui:composition template="/layouts/commonLayout.xhtml">
        <ui:define name="content">
			<h1 align='center'>Add Music Album</h1>
	
			<center>
				<h:form id="form1">
					<h:outputText value="Artist: " />
					<h:inputText id="artist" value="#{album.artist}" />
					<h:message for="artist" style = "color:red" /> 
					<br />
					<br />
					<h:outputText value="Title: " />
					<h:inputText id="title" value="#{album.title}" />
					<h:message for="title" style = "color:red" /> 
					<br />
					<br />
					<h:outputText value="Year: " />
					<h:inputText id="year" value="#{album.year}" minlength="4" />
					<h:message for="year" style = "color:red" /> 
					<br />
					<br />
					<h:commandButton action="#{albumController.onSubmit(album)}" value="Add Album" />
					<h:commandButton action="#{albumController.onFind(album)}" value="Find Album" />
					<h:messages style = "color:red;margin:8px;" /> 
				</h:form>
			</center>

        </ui:define>
    </ui:composition>
</h:body>
</html>

Week_4/Activity 5/activity5/src/main/webapp/AddAlbumResponse.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:ui="http://java.sun.com/jsf/facelets"
	  xmlns:h="http://java.sun.com/jsf/html"
	  xmlns:f="http://java.sun.com/jsf/core">

<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
	<title><ui:insert name="pageTitle">Add Album Response</ui:insert></title>
    <h:outputStylesheet library="css" name="styles.css"/>
</h:head>

<h:body>
    <ui:composition template="/layouts/commonLayout.xhtml">
        <ui:define name="content">
			<h1 align='center'>Add Music Album Response</h1>
			<center>
				<p>Artist: #{album.artist}</p>
				<p>Title: #{album.title}</p>
				<p>Year: #{album.year}</p>
				<p>Track Count: #{album.numberTracks}</p>
				<hr />
				<h:dataTable value="#{album.tracks}" var="track" styleClass="AlbumTracks" id="post_entries">
					<h:column>    				
						<f:facet name = "header">Title</f:facet>    				
						#{track.title}
					</h:column>
					<h:column>
						<f:facet name = "header">Number</f:facet>
						#{track.number}
					</h:column>
				</h:dataTable>
				<h:form id="form2">
					<br />
					<h:commandButton action="AddAlbumForm.xhtml" value="Add Another" />
					<h:messages />
				</h:form>
			</center>
        </ui:define>
    </ui:composition>
</h:body>
</html>

Week_4/Activity 5/activity5/src/main/webapp/Error.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head>
	<title>Common Error Page</title>
</h:head> 
<h:body> 
	<h2 align="center">Common Exception Crash Page</h2>
	
	<h3>Exception Message:</h3>
	#{requestScope['error-message']} <br/>
	
	<h3>Exception Stack:</h3>
	#{requestScope['error-stack']} <br/>
</h:body> 
</html>